# Basic plugin settings
Main_settings:
   # Is the plugin enabled?
   enable: true
   # Is the greeting enabled when launching the plugin in the console?
   enable_greeting: true
   # Logging level
   # Possible values: MINIMAL, STANDARD, DEBUG
   # The number of log message depends on the level
   # At this moment, noone works correctly :-)
   log_level: STANDART
